-- ============================================================
-- Meloscent — Initial Schema
-- Run this in: Supabase Dashboard → SQL Editor
-- ============================================================

-- Perfume catalog
CREATE TABLE IF NOT EXISTS perfumes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  designer    text    NOT NULL,
  name        text    NOT NULL,
  badge       text    NOT NULL,
  mood        text    NOT NULL,
  retail_price integer NOT NULL,
  gradient    text    NOT NULL,
  accent      text    NOT NULL,
  text_col    text    NOT NULL DEFAULT '#FAF3E8',
  card_height integer NOT NULL DEFAULT 440,
  notes_top   text[]  NOT NULL DEFAULT '{}',
  notes_mid   text[]  NOT NULL DEFAULT '{}',
  notes_base  text[]  NOT NULL DEFAULT '{}',
  created_at  timestamptz DEFAULT now()
);

-- Dupe alternatives (many per perfume, app shows best match first)
CREATE TABLE IF NOT EXISTS dupes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfume_id  bigint NOT NULL REFERENCES perfumes(id) ON DELETE CASCADE,
  brand       text   NOT NULL,
  name        text   NOT NULL,
  price_usd   text   NOT NULL,
  match_score integer NOT NULL CHECK (match_score BETWEEN 0 AND 100),
  created_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dupes_perfume_id_idx ON dupes(perfume_id);

-- Blog posts
CREATE TABLE IF NOT EXISTS blog_posts (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category  text     NOT NULL,
  title     text     NOT NULL,
  excerpt   text     NOT NULL,
  gradient  text     NOT NULL,
  read_time text     NOT NULL DEFAULT '5 min read',
  content   text[]   NOT NULL DEFAULT '{}',
  published boolean  NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- User wardrobes — populated once auth is wired up
CREATE TABLE IF NOT EXISTS user_wardrobes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  perfume_id bigint NOT NULL REFERENCES perfumes(id)  ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, perfume_id)
);

-- User engagement stats
CREATE TABLE IF NOT EXISTS user_stats (
  user_id     uuid  PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  flipped_ids bigint[] NOT NULL DEFAULT '{}',
  streak      integer  NOT NULL DEFAULT 0,
  last_visit  date,
  updated_at  timestamptz DEFAULT now()
);

-- ── Row Level Security ────────────────────────────────────────
ALTER TABLE perfumes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE dupes          ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_wardrobes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_stats     ENABLE ROW LEVEL SECURITY;

-- Public catalog reads
CREATE POLICY "perfumes_public_read"
  ON perfumes FOR SELECT USING (true);

CREATE POLICY "dupes_public_read"
  ON dupes FOR SELECT USING (true);

CREATE POLICY "blog_posts_public_read"
  ON blog_posts FOR SELECT USING (published = true);

-- Auth-gated user data (ready for when Supabase Auth is added)
CREATE POLICY "wardrobe_owner_all"
  ON user_wardrobes
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "stats_owner_all"
  ON user_stats
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
